---
name: Tie-Hash-Cannabinol
version: 1.10
author:
  - 'Dave Cross <dave@mag-sol.com>'
abstract: Perl extension for creating hashes that forget things
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Attribute::Handlers: 0
  Tie::Hash: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Tie::Hash::Cannabinol:
    file: lib/Tie/Hash/Cannabinol.pm
    version: 28
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
